#!/usr/bin/python3

import os.path as op

TABLENAME = 'illu67p'
BASE_ACCESS_URL = 'http://cdpp2.cesr.fr/data/illu67p'
SQL_OUTPUT_PATH = '../SERVER/%s_db.sql' % TABLENAME
TXTDATA_PATH = '../DATA/raws/raw-%s.txt'
IMAGE_PATH = '../DATA/images/image-%s.jpg'
PREVIEW_PATH = '../DATA/previews/preview-%s.jpg'
VOTABLE_PATH = '../DATA/votables/votable-%s.xml'

SQL_INIT = """-- File generated by %s.

DROP SCHEMA IF EXISTS %s cascade;
CREATE SCHEMA %s;
SET search_path = public, pg_catalog;
SET default_tablespace = '';
SET default_with_oids = false;

CREATE TABLE %s.data_table (
  id SERIAL PRIMARY KEY,
  subs_longit smallint,
  subs_colat smallint,
  raw_size smallint,
  image_size smallint,
  preview_size smallint,
  votable_size smallint
);

""" % (op.basename(__file__), TABLENAME, TABLENAME, TABLENAME)

SQL_INSERT = 'INSERT INTO ' + TABLENAME \
    + '.data_table(subs_longit, subs_colat, raw_size, image_size, preview_size, votable_size)' \
    + ' VALUES (%s, %s, %s, %s, %s, %s);\n'

with open(SQL_OUTPUT_PATH, 'w+') as f:
    f.write(SQL_INIT)
    for subs_longit in range(0, 360):
        for subs_colat in range(38, 143):
            shortname = '%03d-%03d' % (subs_longit, subs_colat)
            f.write(SQL_INSERT % (subs_longit,
                                  subs_colat,
                                  int(op.getsize(TXTDATA_PATH % shortname)/1024),
                                  int(op.getsize(IMAGE_PATH % shortname)/1024),
                                  int(op.getsize(PREVIEW_PATH % shortname)/1024),
                                  int(op.getsize(TXTDATA_PATH % shortname)/1024))) # TODO replace by the actual votable file size.
